### ISSUE TITLE
Benchmark is too much Write bound

### ISSUE THREAD

**Issue by adnan338** [jabbalaci/SpeedTests#5]
There is a **lot** of unnecessary writes to stdout and this essentially becomes a benchmark of `println` equivalent of different languages.

A language with `println` implementation in the stdlib that

* defaults to a large buffer
* does not lock/unlock the main thread per write operation

will clearly win. Furthermore please keep in mind that different terminal emulators will perform differently at times in the same platform.

I would suggest to somehow keep the writes to a bare minimum.  I am unsure myself what the output actually means.

**Comment by jabbalaci** [comment]
There is one line per one million processed number. So altogether there are 444 printed lines, which is not so many. However, flushes at the end of each line could cause a problem.
I did it because the very first version was written in Python and it was very slow, so I wanted to see some feddback that it's doing something.

**Comment by jabbalaci** [comment]
@adnan338 The debug output was removed and the programs became much faster. Thanks for your comment. The tests were re-run and the README was updated with the new values.

Lesson learned: even 450 printed lines can make your program much slower.
